Repository shashank6341/soen-6611, pull requests merged in 2023-11, with the labels that each got.

#10 Implement base metricstics
  Code/metricstics_calc.py
Labels: Develop

#11 Implement Likert Scale #8
  Code/likert-scale/package-lock.json
  Code/likert-scale/package.json
  Code/likert-scale/public/index.html
  Code/likert-scale/server.js
Labels: Develop

#18 Fix for Issue #17
  Code/metricstics.py
Labels: bug

#21 Integrate Login Window - #12
  Code/calculations.csv
  Code/login.py
  Code/metricstics.py
Labels: Develop

#31 Added SLOC Images
  Code/Images/Iteration 1.1.png
  Code/Images/Iteration 1.2.png
  Code/Images/Iteration 1.3.png
  Code/Images/Iteration 1.4.png
  Code/Images/Iteration 2.1.png
  Code/Images/Iteration 2.2.png
  Code/Images/Iteration 2.3.png
  Code/Images/Iteration 2.4.png
  Code/Images/Iteration 3.1.png
  Code/Images/Iteration 3.2.png
  Code/Images/Iteration 3.3.png
  Code/Images/Iteration 3.4.png
Labels: documentation
